# **2.20 Numpy**

**2.20.1 Perintah Dasar pada Numpy**

In [137]:
# dimensi 1
import numpy as np
array_y_07 = np.array([5,15,25,35,45,55])
dimensi_y_07 = print("Dimensi:", array_y_07.ndim)
ukuran_array_y_07 = print("Ukuran:", array_y_07.shape)

Dimensi: 1
Ukuran: (6,)


In [138]:
# dimensi 2
import numpy as np
x_array_07 = np.array([[12,56],[14,78],[34,28]])
tampil_x_array_07 = print(x_array_07)
dimensi_x_07 = print("Dimensi:", x_array_07.ndim)
ukuran_array_x_07 = print("Ukuran:", x_array_07.shape)
print("---------------------------------------------------")
r_array_07 = np.array([[120,36,200],[61,98,34]])
tampil_r_array_07 = print(r_array_07)
dimensi_r_07 = print("Dimensi:", r_array_07.ndim)
ukuran_array_r_07 = print("Ukuran:", r_array_07.shape)

[[12 56]
 [14 78]
 [34 28]]
Dimensi: 2
Ukuran: (3, 2)
---------------------------------------------------
[[120  36 200]
 [ 61  98  34]]
Dimensi: 2
Ukuran: (2, 3)


In [139]:
# dimensi 3
import numpy as np
a_array_07 = np.array([[[-5,6],[-1,7]]])
tampil_a_array_07 = print(a_array_07)
dimensi_a_07 = print("Dimensi:", a_array_07.ndim)
ukuran_array_a_07 = print("Ukuran:", a_array_07.shape)
print("===================================================")
b_array_07 = np.array([[[-5,6],[-1,7],[3,6]]])
tampil_b_array_07 = print(b_array_07)
dimensi_b_07 = print("Dimensi:", b_array_07.ndim)
ukuran_array_b_07 = print("Ukuran:", b_array_07.shape)

[[[-5  6]
  [-1  7]]]
Dimensi: 3
Ukuran: (1, 2, 2)
[[[-5  6]
  [-1  7]
  [ 3  6]]]
Dimensi: 3
Ukuran: (1, 3, 2)


In [140]:
# dimensi 3
c_array_07 = np.array([[[-5,6,2],[-1,7,8],[2,0,2]],
                      [[0,1,0],[4,7,9],[1,0,0]]])
tampil_c_array_07 = print(c_array_07)
dimensi_c_07 = print("Dimensi:", c_array_07.ndim)
ukuran_array_c_07 = print("Ukuran:", c_array_07.shape)
print("===================================================")
d_array_07 = np.array([[[-5,6,2],[-1,7,8]],
                      [[0,1,0],[4,7,9]],
                      [[3,6,5],[0,2,7]]])
tampil_d_array_07 = print(d_array_07)
dimensi_d_07 = print("Dimensi:", d_array_07.ndim)
ukuran_array_d_07 = print("Ukuran:", d_array_07.shape)

[[[-5  6  2]
  [-1  7  8]
  [ 2  0  2]]

 [[ 0  1  0]
  [ 4  7  9]
  [ 1  0  0]]]
Dimensi: 3
Ukuran: (2, 3, 3)
[[[-5  6  2]
  [-1  7  8]]

 [[ 0  1  0]
  [ 4  7  9]]

 [[ 3  6  5]
  [ 0  2  7]]]
Dimensi: 3
Ukuran: (3, 2, 3)


**2.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy**

In [141]:
import numpy as np
y_array_07 = np.array([5,-15,-25,35,-45,-55])
anggota_array_kelima_07 = print("Anggota/nilai ke-5:", y_array_07[5])

Anggota/nilai ke-5: -55


In [142]:
# dimensi 2
import numpy as np
w_array_07 = np.array([[12,16],[1,0],[14,18]])
tampil_w_array_07 = print(w_array_07)
panggil_baris_07 = print("Baris pertama (W):", w_array_07[0,:])
panggil_kolom_kelima_07 = print("Kolom pertama (W):", w_array_07[:,0])
panggil_baris_kolom_07 = print("Baris pertama dan kolom pertama (W):", w_array_07[0,0])
print("=======================================")
n_array_07 = np.array([[120,36,200],[61,98,34]])
tampil_n_array_07 = print(n_array_07)
panggil_baris_07 = print("Baris kedua (N):", n_array_07[1,:])
panggil_kolom_kelima_07 = print("Kolom pertama (N):", n_array_07[:,0])
panggil_baris_kolom_07 = print("Baris kedua dan kolom pertama (N):", n_array_07[1,0])

[[12 16]
 [ 1  0]
 [14 18]]
Baris pertama (W): [12 16]
Kolom pertama (W): [12  1 14]
Baris pertama dan kolom pertama (W): 12
[[120  36 200]
 [ 61  98  34]]
Baris kedua (N): [61 98 34]
Kolom pertama (N): [120  61]
Baris kedua dan kolom pertama (N): 61


In [143]:
import numpy as np
array_07 = np.array([[-5,6,2],
                     [-1,7,8],
                     [2,0,2]])
tampil_array_07 = print(array_07)
def panggil_nilai_07(baris, kolom):
  if baris < 0 or kolom < 0 or baris >= array_07.shape[0] or kolom >= array_07.shape[0]:
    return ("Sudah di luar batas array")
  return array_07[baris, kolom]
input_baris_07 = int(input("Masukkan nomor baris keberapa diantara 0-2: "))
input_kolom_07 = int(input("Masukkan nomor kolom keberapa diantara 0-2: "))
nilai_array_07 = panggil_nilai_07(input_baris_07, input_kolom_07)
hasil_array_07 = print(f"Hasil di baris ke {input_baris_07} dan kolom ke {input_kolom_07} adalah: {nilai_array_07}")

[[-5  6  2]
 [-1  7  8]
 [ 2  0  2]]
Masukkan nomor baris keberapa diantara 0-2: 1
Masukkan nomor kolom keberapa diantara 0-2: 0
Hasil di baris ke 1 dan kolom ke 0 adalah: -1


**2.20.3  Matrix pada Numpy**

In [144]:
# buat matriks 3x3
import numpy as np
w_07 = np.zeros((3,3))
print(w_07)
print(" ")
o_07 = np.identity(3)
print(o_07)
print(" ")
n_07 = 7*o_07
print(n_07)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
[[7. 0. 0.]
 [0. 7. 0.]
 [0. 0. 7.]]


**2.20.4 Copy pada Numpy**

In [145]:
import numpy as np
f_07 = np.array([-10,-9,-8,-7])
g_07 = f_07.copy()
g_07[2] = -6
print(g_07)

[-10  -9  -6  -7]


**2.20.5 Operasi Matematika pada Numpy**

In [146]:
import numpy as np
y_07 = np.array([5,15,-25,-35,45,55])
operasi_nilai_07 = y_07/5
hasil_operasi_nilai_07 = print (f"Hasil operasi array: {operasi_nilai_07}")

Hasil operasi array: [ 1.  3. -5. -7.  9. 11.]


In [147]:
import numpy as np
p_07 = np.array([5,4,-2,-3,4,5])
h_07 = np.array([0,1,0,2,0,3])
operasi_nilai_07 = p_07+h_07
hasil_operasi_nilai_07 = print (f"Hasil operasi array: {operasi_nilai_07}")

Hasil operasi array: [ 5  5 -2 -1  4  8]


**2.20.6 Perkalian Matrik pada Numpy**

In [148]:
import numpy as np
j_07 = np.array([[7, 1, 0],
                 [0, 7, 1],
                 [1, 0, 7],
                 [0, 0, 1]])
u_07 = np.array ([[2, 4, 1, 0],
                  [0, 8, 5, 2],
                  [3, 2, 0, 0]])
print(j_07)
print(" ")
print(u_07)
print(" ")
hasil_kali_07 = np.matmul(j_07, u_07)
tampil_hasil_07 = print(hasil_kali_07)


[[7 1 0]
 [0 7 1]
 [1 0 7]
 [0 0 1]]
 
[[2 4 1 0]
 [0 8 5 2]
 [3 2 0 0]]
 
[[14 36 12  2]
 [ 3 58 35 14]
 [23 18  1  0]
 [ 3  2  0  0]]


**2.20.7 min, max dan sum pada Numpy**

In [149]:
import numpy as np
d_07 = np.array([[120,-20,0],[6,9,34]])
m_07 = np.max(d_07)
print(m_07)

120


In [150]:
import numpy as np
q_07 = np.array([[120,-20,0],[6,9,34],[0,1,4]])
h_07 = np.sum(q_07, axis=1)
print(h_07)

[100  49   5]
